### ISSUE TITLE
Alternate view feature request + 'open in finder' feature request

### ISSUE THREAD

**Issue by ctrpetersen** [deseven/iCanHazMusic#10]
Hi, first of all, thank you for making this software. It's now my daily driver, after, like you, having been around most music players for mac (also coming from Foobar2k on Win :)) and finding them all unsatisfactory. Latest one being Swinsian, which was pretty good -- except it was missing a 'cursor follows playback' feature, which is very important to me.

One thing I'd love to see would be an alternative view option for the main window, where it's not separated into albums, just one large list. Maybe grouped by album would be nice.
Another feature which I'd love would be a right-click option to open the folder which the corresponding track is located.

Additionally, global media key shortcuts would be fantastic - I see they're in the planned later section in the readme, just wondering what the status is.
(One minor thing -- in the File-> dropdown, it says 'Open diectory', which should probably be 'Open directory')

I'm not sure if any of these have been added with recent commits, as I see the newest release is somewhat older than a lot of commits. I've tried building from source, but had issues with the PB compiler, probably as I've no experience with PB (nor xcode, for that matter).

Thank you again for the software and sharing it, it fits perfectly what I've been looking for, a nice mix of simplicity with feature richness. I was especially happy to see the performance being great - scrolling through a ~5k track playlist without a hitch, in stark contrast to some of the other music players I've tried.

**Comment by deseven** [comment]
Hi :)

> One thing I'd love to see would be an alternative view option for the main window, where it's not separated into albums, just one large list. Maybe grouped by album would be nice.

What do you mean by "grouped by album"? Isn't it grouped by album right now?

> Another feature which I'd love would be a right-click option to open the folder which the corresponding track is located.

Yeah, I will add that for sure.

> Additionally, global media key shortcuts would be fantastic - I see they're in the planned later section in the readme, just wondering what the status is.

I plan to add customizable hotkeys soon™, but media keys are out of the question right now because apparently there is no way to do the required things in PB. This might change pretty soon, though, with the new C-based pbcompiler.

> One minor thing -- in the File-> dropdown, it says 'Open diectory', which should probably be 'Open directory'

Nice catch!

> I'm not sure if any of these have been added with recent commits, as I see the newest release is somewhat older than a lot of commits

Yeah, well... Since I don't see too much interest I don't do releases regularly, also there is no significant progress. But I compiled the latest dev build for you, I use it daily.

[ichm-040-dev.zip](https://github.com/deseven/iCanHazMusic/files/8226991/ichm-040-dev.zip)

**Comment by ctrpetersen** [comment]
Thank you for the response, and the release! 
What I mean by the view is the ability to disable the 'separators', marked here in red https://i.imgur.com/22qa4p1.png. A lot of my music is unfortunately pretty poorly tagged, which leads to the main view looking a bit messy.
Thanks for the update on media keys, it's not a huge deal (and shortcuts would be fine as well).

**Comment by deseven** [comment]
Ah, I see. I was thinking about some option to enable/disable album grouping, I'll try adding one in the near future.  
Thanks for the feedback, much appreciated!

**Comment by deseven** [comment]
Okay, so, I was thinking about just hiding album separators on the view level, but looks like it brings more pain than needed. So instead I just remove such entries from the playlist altogether. Seems to be working, but unexpected bugs may arise for sure. The option to disable album grouping is available in the "Playlist" menu.

It's now also possible to reveal a file or album in Finder.

Please help with testing if you can and report any problems.

[ichm-040-dev.zip](https://github.com/deseven/iCanHazMusic/files/8239819/ichm-040-dev.zip)

**Comment by ctrpetersen** [comment]
Thank you for the release! I've been using it today and haven't noticed any problems regarding these 2 new features.

2 issues regarding other features I've noticed are:

Album art doesn't seem to update if selecting a track with none. From a fresh start, if only selecting tracks with album art, it updates correctly. However, once a track with none is selected, it will never update again until restarting, showing the album art of the track selected last, even if selecting other tracks with album art again. This only occurs if any tracks are missing album art. 

Some tracks are missing the title. I suspect this is due to missing tags. Maybe a fallback to the actual filename if tags are missing?

**Comment by deseven** [comment]
Haven't looked at those issues you found yet, but global shortcuts are available now (no media keys though).

[ichm-040-dev.zip](https://github.com/deseven/iCanHazMusic/files/8549860/ichm-040-dev.zip)

**Comment by deseven** [comment]
Ok, I found the problem with album art and fixed it.

However, I won't be doing anything special for the lack of tags, sorry. Writing some complicated logic that tries to populate needed fields is not something I personally need, and simply putting a filename there is totally wrong. Also this forces you to actually keep your library clean.

Still, I changed default values to "Unknown Artist" and "Unknown Title" as they are more neutral and no error should be outputted to playlist fields.

I'm going to close this issue, please feel free to create a new one if needed, just please try to limit 1 issue per 1 problem.
