### ISSUE TITLE
No filename track info shown

### ISSUE THREAD

**Issue by m0rg5** [deseven/iCanHazMusic#15]
Just had the same tracks in museeks and it detected filenames fine, ICHM detected none.

<img width="824" alt="Screen Shot 2022-10-23 at 8 36 59 am" src="https://user-images.githubusercontent.com/8669538/197363301-93e5e62f-7029-4a36-8458-39d4097bf1fc.png">

**Comment by deseven** [comment]
I have no plans for filenames to be processed in any way. Keep your tags clean or use another audio player, iCHM is not designed for this use case, sorry.
